apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-pxdocs-3.0
  namespace: pxdocs
spec:
  secretName: ingress-pxdocs-3.0-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
  - 3.0.docs.portworx.com