apiVersion: v1
kind: Service
metadata:
  name: docs-${TRAVIS_PULL_REQUEST}
  namespace: pxdocs-staging
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: docs-${TRAVIS_PULL_REQUEST}
