apiVersion: v1
kind: Service
metadata:
  name: pds-${VERSIONS_TAG}
  namespace: pxdocs-pds
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    name: pds-port
  selector:
    app: pds-${VERSIONS_TAG}

