apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: pxcentral-ingress
  namespace: pxdocs-central
spec:
  rules:
  - host: central.docs.portworx.com
    http:
      paths:
      - backend:
          serviceName: pxcentral-1-3
          servicePort: 80
        path: /
  tls:
  - hosts:
    - backup.docs.portworx.com
    secretName: ingress-pxbackup-tls
  - hosts:
    - 1.3.backup.docs.portworx.com
    secretName: ingress-pxbackup-1.3 
